spring:
  application:
    name: auth


oauth2:
  provider:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      grant-type: ${GOOGLE_GRANT_TYPE}
      uri:
        token-endpoint: ${GOOGLE_TOKEN_ENDPOINT}
        redirect-uri: ${GOOGLE_REDIRECT_URI}
        user-info-endpoint: ${GOOGLE_USER_INFO_ENDPOINT}